server:
  servlet:
    context-path: /sample
  port: 8110

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

auth:
  jwt:
    secret: UTaRvhs43PxSEA5n
    expiration-ms: 604800000
